-- TakeCare initial schema: tables, indexes, RLS policies.
-- See docs/build-spec.md section 5.

create table patients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  timezone text not null default 'Asia/Kolkata'
);

create table medicines (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid references patients(id) not null,
  name text not null,
  dosage_per_intake integer not null,
  times_per_day text[] not null,
  current_stock integer not null,
  refill_threshold_days integer not null default 7,
  low_stock_alert_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index medicines_patient_id_idx on medicines(patient_id);

create table intake_logs (
  id uuid primary key default gen_random_uuid(),
  medicine_id uuid references medicines(id) not null,
  scheduled_time timestamptz not null,
  taken_time timestamptz,
  status text not null check (status in ('pending','taken','missed')) default 'pending',
  created_at timestamptz not null default now(),
  unique (medicine_id, scheduled_time)
);

create index intake_logs_medicine_id_idx on intake_logs(medicine_id);
create index intake_logs_status_scheduled_time_idx on intake_logs(status, scheduled_time);

create table family_members (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid references patients(id) not null,
  name text not null,
  auth_user_id uuid references auth.users(id) not null unique,
  created_at timestamptz not null default now()
);

create index family_members_patient_id_idx on family_members(patient_id);

create table push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  family_member_id uuid references family_members(id) not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

create index push_subscriptions_family_member_id_idx on push_subscriptions(family_member_id);

-- ---------------------------------------------------------------------------
-- RLS helper: returns the patient_id linked to the calling auth user.
-- SECURITY DEFINER so it can read family_members without recursing through
-- that table's own RLS policy (which itself calls this function).
-- ---------------------------------------------------------------------------
create or replace function my_patient_id()
returns uuid
language sql
security definer
set search_path = public
stable
as $$
  select patient_id from family_members where auth_user_id = auth.uid() limit 1;
$$;

alter table patients enable row level security;
alter table medicines enable row level security;
alter table intake_logs enable row level security;
alter table family_members enable row level security;
alter table push_subscriptions enable row level security;

-- patients: readable by any authenticated user (name/timezone only, low
-- sensitivity) so a first-time login can discover the single v1 patient and
-- bootstrap its own family_members row.
create policy "patients_select_authenticated"
  on patients for select
  to authenticated
  using (true);

-- family_members: a user can always see their own row, plus every row that
-- shares their patient once they're linked.
create policy "family_members_select"
  on family_members for select
  to authenticated
  using (auth_user_id = auth.uid() or patient_id = my_patient_id());

-- self-registration: a signed-in user may create their own family_members
-- row (and only their own).
create policy "family_members_insert_self"
  on family_members for insert
  to authenticated
  with check (auth_user_id = auth.uid());

create policy "family_members_update_self"
  on family_members for update
  to authenticated
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

-- medicines: full CRUD for any family member of the same patient.
create policy "medicines_select"
  on medicines for select
  to authenticated
  using (patient_id = my_patient_id());

create policy "medicines_insert"
  on medicines for insert
  to authenticated
  with check (patient_id = my_patient_id());

create policy "medicines_update"
  on medicines for update
  to authenticated
  using (patient_id = my_patient_id())
  with check (patient_id = my_patient_id());

create policy "medicines_delete"
  on medicines for delete
  to authenticated
  using (patient_id = my_patient_id());

-- intake_logs: read-only for the client. Rows are generated by the daily
-- dose-generation cron job and mutated by the log-intake / check-missed-doses
-- Edge Functions, both of which use the service role key and so bypass RLS.
create policy "intake_logs_select"
  on intake_logs for select
  to authenticated
  using (
    medicine_id in (select id from medicines where patient_id = my_patient_id())
  );

-- push_subscriptions: a family member manages only their own subscriptions.
create policy "push_subscriptions_select"
  on push_subscriptions for select
  to authenticated
  using (
    family_member_id in (select id from family_members where auth_user_id = auth.uid())
  );

create policy "push_subscriptions_insert"
  on push_subscriptions for insert
  to authenticated
  with check (
    family_member_id in (select id from family_members where auth_user_id = auth.uid())
  );

create policy "push_subscriptions_update"
  on push_subscriptions for update
  to authenticated
  using (
    family_member_id in (select id from family_members where auth_user_id = auth.uid())
  )
  with check (
    family_member_id in (select id from family_members where auth_user_id = auth.uid())
  );

create policy "push_subscriptions_delete"
  on push_subscriptions for delete
  to authenticated
  using (
    family_member_id in (select id from family_members where auth_user_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Daily dose generation.
--
-- The build spec's Edge Functions only ever update existing intake_logs rows
-- (log-intake, check-missed-doses) -- nothing creates the 'pending' row for
-- each scheduled dose in the first place. This function does that: for every
-- medicine, for every time in times_per_day, it inserts today's pending row
-- (in the patient's timezone), skipping ones that already exist.
-- Scheduled once daily via pg_cron in 0002_cron.sql.
-- ---------------------------------------------------------------------------
create or replace function generate_todays_doses()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  med record;
  time_str text;
  scheduled timestamptz;
begin
  for med in
    select m.id, m.times_per_day, p.timezone
    from medicines m
    join patients p on p.id = m.patient_id
  loop
    foreach time_str in array med.times_per_day
    loop
      scheduled := (
        (now() at time zone med.timezone)::date::text || ' ' || time_str
      )::timestamp at time zone med.timezone;

      insert into intake_logs (medicine_id, scheduled_time, status)
      values (med.id, scheduled, 'pending')
      on conflict (medicine_id, scheduled_time) do nothing;
    end loop;
  end loop;
end;
$$;
